-d C:\Users\rulisso\Documents\FPGA\Aula01\Aula01\impl\gwsynthesis\Aula01.vg
-p GW1N-1-QFN48-6
-pn GW1N-LV1QN48C6/I5
-cst C:\Users\rulisso\Documents\FPGA\Aula01\Aula01\src\my_and.cst
-cfg C:\Users\rulisso\Documents\FPGA\Aula01\Aula01\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
-cst_error
